### ISSUE TITLE
Deprecation notices

### ISSUE THREAD

**Issue by OllieJones** [OllieJones/index-wp-mysql-for-speeed#55]
[titsmaker](https://wordpress.org/support/users/titsmaker/) (@titsmaker) reports
 
https://wordpress.org/support/topic/php-8-1-compatibility-16/

Hi, currently the plugin throws following deprecation notice under PHP 8.1:

Deprecated: parse_str(): Passing null to parameter #1 ($string) of type string is deprecated in \wp-content\plugins\index-wp-mysql-for-speed\afp\factory\_common\_abstract\_model\AdminPageFramework_Property_Base.php on line 79

and 

BTW, there are some deprecations related to PHP 8.2 as well:

Deprecated: Using ${var} in strings is deprecated, use {$var} instead in \wp-content\plugins\index-wp-mysql-for-speed\code\rendermonitor.php on line 113
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in \wp-content\plugins\index-wp-mysql-for-speed\code\getqueries.php on line 209
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in \wp-content\plugins\index-wp-mysql-for-speed\code\getqueries.php on line 202
Deprecated: Using ${var} in strings is deprecated, use {$var} instead in \wp-content\plugins\index-wp-mysql-for-speed\code\getqueries.php on line 189

**Comment by Drivingralle** [comment]
Hey!
As far as I understand this ticket should be fixed in Version 1.4.12, right?

Today I installed the plugin on a localWP with PHP 8.1.9 and still got the "Deprecated: parse_str(): Passing null to parameter https://github.com/OllieJones/index-wp-mysql-for-speed/issues/1 ($string) of type string is deprecated".

Greetings
derRALF

**Comment by OllieJones** [comment]
OK, I'll take another look. Thanks.

**Comment by rjasdf** [comment]
If you have any "classes", check their constructors.

**Comment by himanshu-mahendra-jain** [comment]
Getting these errors with the latest version, @OllieJones. Admin Page Framework has not fixed them at the source yet. [You can find the unresolved issues here: https://github.com/michaeluno/admin-page-framework](https://github.com/michaeluno/admin-page-framework/issues/298). Perhaps you can push the fixes upstream or create a fork with the necessary fixes."

```
Deprecated: Creation of dynamic property Imfs_AdminPageFramework_Form_admin_page::$aSections is deprecated in /var/www/html/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/admin_page/AdminPageFramework.php on line 85

Deprecated: Creation of dynamic property ImfsDb::$tableFormats is deprecated in /var/www/html/wp-content/plugins/index-wp-mysql-for-speed/code/imsfdb.php on line 53

Deprecated: Creation of dynamic property ImfsPage::$pluginUpgrading is deprecated in /var/www/html/wp-content/plugins/index-wp-mysql-for-speed/code/admin.php on line 394

Deprecated: Creation of dynamic property Imfs_AdminPageFramework_TabNavigationBar::$aActiveSlugs is deprecated in /var/www/html/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/_abstract/_view/AdminPageFramework_TabNavigationBar.php on line 16

Deprecated: strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/form/_view/sectionset/AdminPageFramework_Form_View___FieldTitle.php on line 33

Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/wp-content/plugins/index-wp-mysql-for-speed/afp/factory/_common/utility/base_utility/AdminPageFramework_Utility.php on line 570
```

**Comment by OllieJones** [comment]
Fixed these, and sent a PR to https://github.com/michaeluno/admin-page-framework/issues/298. Will appear in next release.
